# Generated by Django 5.1.5 on 2025-02-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicecategory_slug_categoryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryimage',
            old_name='product',
            new_name='category',
        ),
    ]
