# Generated by Django 5.1.5 on 2025-02-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_service_alter_categoryimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.servicecategory'),
        ),
    ]
