# Generated by Django 5.1.5 on 2025-02-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_workers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workers',
            new_name='Worker',
        ),
    ]
