# Generated by Django 5.1.5 on 2025-02-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_workers_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
