# Generated by Django 5.1.5 on 2025-02-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_service_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
