# Generated by Django 5.1.5 on 2025-02-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_service_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
