# Generated by Django 5.1.5 on 2025-02-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_booking_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="time",
            field=models.CharField(default=None, max_length=30),
        ),
    ]
