# Generated by Django 5.1.5 on 2025-02-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_booking_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("1", "Pending"), ("2", "Approved"), ("3", "Denied")],
                default="1",
                max_length=30,
            ),
        ),
    ]
